### ISSUE TITLE
Specs section in bet.tests.move are not used in sui move?

### ISSUE THREAD

**Issue by georgescharlesbrain** [juzybits/polymedia-gotbeef#3]
The [specs](https://github.com/juzybits/polymedia-gotbeef/blob/b9ede32db0b9baf329e614142aa419cd6be05ece/sui/sources/bet.tests.move#L584) are not relevant for sui move right?
These are just leftover comments from a solidity implementation?

**Comment by juzybits** [comment]
That was me trying to use the Move prover, but prover support for the Sui framework was incomplete, so I gave up.

https://github.com/move-language/move/blob/main/language/move-prover/doc/user/prover-guide.md
https://github.com/move-language/move/blob/main/language/move-prover/doc/user/spec-lang.md
